
spring:

  # DB
  datasource:
    url: jdbc:h2:mem:mydb
    username:
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      format_sql: true
      ddl-auto: create

  h2:
    console:
      enabled: true


# 로깅
logging:
  level:
    org.hibernate.SQL: DEBUG
    orf.hibernate.type.descriptor.sql.BasicBinder: TRACE



